# Generated by Django 4.0.6 on 2022-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa'), ('Stripe', 'Stripe')], default='Cash On Delivery', max_length=20),
        ),
    ]
